//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderDatabaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster_Attacks
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string To_Hit { get; set; }
        public Nullable<long> Dice_Count { get; set; }
        public Nullable<long> Dice_Value { get; set; }
        public Nullable<long> Bonus_Damage { get; set; }
        public Nullable<int> Lower_Crit_Range { get; set; }
        public string Additional_Effects { get; set; }
        public Nullable<int> Attack_Group_ID { get; set; }
    
        public virtual Monster_Attack_Groups Monster_Attack_Groups { get; set; }
    }
}
