//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderDatabaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster_Attack_Groups
    {
        public Monster_Attack_Groups()
        {
            this.Monster_Attacks = new HashSet<Monster_Attacks>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Monster_ID { get; set; }
    
        public virtual Monster Monster { get; set; }
        public virtual ICollection<Monster_Attacks> Monster_Attacks { get; set; }
    }
}
