//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderDatabaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public Monster()
        {
            this.Monster_Attack_Groups = new HashSet<Monster_Attack_Groups>();
            this.Monster_Additional_Notes = new HashSet<Monster_Additional_Notes>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<long> Initiative { get; set; }
        public string Senses { get; set; }
        public string Auras { get; set; }
        public string AC { get; set; }
        public Nullable<long> HP { get; set; }
        public Nullable<long> HD { get; set; }
        public string HP_Mods { get; set; }
        public Nullable<long> Fortitude { get; set; }
        public Nullable<long> Reflex { get; set; }
        public Nullable<long> Will { get; set; }
        public string Save_Mods { get; set; }
        public string Defenses { get; set; }
        public string Defensive_Abilities { get; set; }
        public string Weaknesses { get; set; }
        public string Speed { get; set; }
        public string Space { get; set; }
        public string Reach { get; set; }
        public Nullable<long> Base_Attack { get; set; }
        public Nullable<long> CMB { get; set; }
        public string CMB_Mods { get; set; }
        public string CMD { get; set; }
        public string Special_Attacks { get; set; }
        public string Special_Qualities { get; set; }
        public string Ability_Scores { get; set; }
        public string Feats { get; set; }
        public string Skills { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Monster_Attack_Groups> Monster_Attack_Groups { get; set; }
        public virtual ICollection<Monster_Additional_Notes> Monster_Additional_Notes { get; set; }
    }
}
