//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderDatabaseManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pathfinder_managerEntities : DbContext
    {
        public pathfinder_managerEntities()
            : base("name=pathfinder_managerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Monster_Attack_Groups> Monster_Attack_Groups { get; set; }
        public virtual DbSet<Monster_Attacks> Monster_Attacks { get; set; }
        public virtual DbSet<Monster> Monsters { get; set; }
        public virtual DbSet<Monster_Additional_Notes> Monster_Additional_Notes { get; set; }
        public virtual DbSet<Monster_Names> Monster_Names { get; set; }
    }
}
